apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: aman3105/nginx-nnr
        ports:
          - containerPort: 80
          
      #   env:
      #     - name: flask_server_addr
      #       value: "flask:9091"
      #   volumeMounts:
      #     - name: my-config
      #       mountPath: "/etc/nginx/conf.d/default.conf"
      #       subPath: nginx.conf
      #       readOnly: true
      #   ports:
      #   - containerPort: 80
      # volumes:
      #   - name: my-config
      #     configMap: 
      #       name: my-config