apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodejs-sts
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: aman3105/nodejs-nnr
        ports:
        - containerPort: 5000
